name: Papatone Marketing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75813
title: papatone marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f6f2'
    - '#000000'
    - '#908a87'
    - '#acb9c1'
    - '#084b3b'
  brandStrength: 1
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
